name: Pipeline

on:
  pull_request: #trigger on pull requests to the branch
    branches:
      - main
  schedule: #trigger by schedule at midnight
    - cron: "0 0 * * *"
  workflow_dispatch: #manually trigger the workflow
    inputs:
      browser:
        description: "Select browser to run UI tests against"
        required: true
        default: "chrome"
        type: string
        options:
          - chrome
          - firefox
          - edge

env:
  BROWSER: ${{ github.event.inputs.browser || 'chrome' }}

jobs:
  test-suite:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' 

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxi6

          echo "Selected browser: $BROWSER"
          
          if [ "$BROWSER" == "chrome" ]; then
            echo "Installing Chrome..."
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            wget https://chromedriver.storage.googleapis.com/120.0.6099.109/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver

          elif [ "$BROWSER" == "firefox" ]; then
            echo "Installing Firefox..."
            sudo apt-get install -y firefox
            wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
            tar -xvzf geckodriver-v0.30.0-linux64.tar.gz
            sudo mv geckodriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/geckodriver

          elif [ "$BROWSER" == "edge" ]; then
            echo "Installing Edge..."
            wget -q -O - https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
            sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/
            sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-stable.list'
            sudo apt-get update
            sudo apt-get install -y microsoft-edge-stable
            wget https://msedgedriver.azureedge.net/114.0.1823.43/edgedriver_linux64.zip
            unzip edgedriver_linux64.zip
            sudo mv msedgedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/msedgedriver
          else
            echo "Unknown browser:$BROWSER"
            exit 1
          fi
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build 
        run: dotnet build --no-restore 
        working-directory: .

      - name: Run API Tests
        run: dotnet test --filter "Category=API" --logger "trx;LogFileName=api-tests.trx"
        continue-on-error: true

      - name: Run UI Tests
        run: dotnet test --filter "Category!=API" --logger "trx;LogFileName=ui-tests.trx"

      - name: Debug Artifact Generation
        run: |
          echo "Checking artifact directories and contents..."
          echo "Logs directory:"
          ls -la Logs || echo "Logs directory does not exist."
          echo "Screenshots directory:"
          ls -la Screenshots || echo "Screenshots directory does not exist."
          
      - name: Upload Logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: Logs/
          
      - name: Upload Screenshots (if any)
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: Screenshots/
